name: Java CI/CD with Docker

on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: manivannank/github-action-docker-ec2
  CONTAINER_NAME: github-action-docker-ec2
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Analyze with SonarCloud
      run: mvn clean verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Image to ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Clean up old containers and images to save disk space
          docker stop ${{ secrets.ECR_REPOSITORY }} || true
          docker rm ${{ secrets.ECR_REPOSITORY }} || true
          docker system prune -f || true

          # Authenticate Docker on the EC2 instance with AWS ECR
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

          # Pull the latest image
          docker pull ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}://{{ secrets.ECR_REPOSITORY }}:latest

          # Stop old container (if running) 
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

          
          # Run the new container (Adjust the port mapping -p as per your application configuration)
          docker run -d --name ${{ secrets.ECR_REPOSITORY }} -p 80:8000 --restart unless-stopped ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}://{{ secrets.ECR_REPOSITORY }}:latest